Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("tuition").Set "400" @@ hightlight id_;_Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("tuition")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("books").Set "250" @@ hightlight id_;_Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("books")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("utilities").Set "600" @@ hightlight id_;_Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("utilities")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("food").Set "150" @@ hightlight id_;_Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("food")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("clothing").Set "750" @@ hightlight id_;_Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("clothing")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("federalloans").Set "0" @@ hightlight id_;_Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("federalloans")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("jobincome").Set "1000" @@ hightlight id_;_Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("jobincome")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("savings").Set "200" @@ hightlight id_;_Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").WebEdit("savings")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").Link("Calculate  (Updates page").Click @@ hightlight id_;_Browser("Student Loans Budget Calculato").Page("Student Loans Budget Calculato").Link("Calculate  (Updates page")_;_script infofile_;_ZIP::ssf9.xml_;_
wait

